services:
  backend:
    container_name: polymorphix-backend
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - server/.env
    volumes:
      - ./server/app:/server/app
      - ./server/main.py:/server/main.py
      - ./server/prisma:/server/prisma
      - ./server/.env:/server/.env
      - polymorphix_shared_data:/video_queue
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8080 --reload
    depends_on:
      - rabbitmq
    networks:
      - polymorphix-network

  rabbitmq:
    container_name: "polymorphix-rabbitmq"
    image: rabbitmq:4.2.2-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - polymorphix_rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - polymorphix-network

  prisma_studio:
    container_name: polymorphix-prisma-studio
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    env_file:
      - server/.env
    volumes:
      - ./server/prisma:/server/prisma
      - ./server/.env:/server/.env
    command: uv run prisma studio --port 5555 --browser none
    networks:
      - polymorphix-network

  celery_transcode_worker:
    container_name: polymorphix-celery-transcoder-worker
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uv run celery -A app.tasks.celery_app worker -Q celery --loglevel=info
    env_file:
      - server/.env
    environment:
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq//
    volumes:
      - ./server/app:/server/app
      - ./server/main.py:/server/main.py
      - ./server/prisma:/server/prisma
      - ./server/.env:/server/.env
      - polymorphix_shared_data:/video_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - polymorphix-network

  celery_upload_worker:
    container_name: polymorphix-celery-upload-worker
    build:
      context: ./server
      dockerfile: Dockerfile
    command: uv run celery -A app.tasks.celery_app worker -Q upload --loglevel=info
    env_file:
      - server/.env
    environment:
      - CELERY_BROKER_URL=pyamqp://guest:guest@rabbitmq//
    volumes:
      - ./server/app:/server/app
      - ./server/main.py:/server/main.py
      - ./server/prisma:/server/prisma
      - ./server/.env:/server/.env
      - polymorphix_shared_data:/video_queue
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - polymorphix-network

volumes:
  polymorphix_shared_data:
    name: polymorphix_shared_data
    driver: local

  polymorphix_rabbitmq_data:
    name: polymorphix_rabbitmq_data
    driver: local

networks:
  polymorphix-network:
    name: polymorphix-network
    driver: bridge
